// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// weighted_mean_cpp
double weighted_mean_cpp(NumericVector x, NumericVector weights);
RcppExport SEXP _rankingQ_weighted_mean_cpp(SEXP xSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_mean_cpp(x, weights));
    return rcpp_result_gen;
END_RCPP
}
// weighted_var_cpp
double weighted_var_cpp(NumericVector x, NumericVector weights);
RcppExport SEXP _rankingQ_weighted_var_cpp(SEXP xSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_var_cpp(x, weights));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_indicator_cpp
NumericVector pairwise_indicator_cpp(NumericVector target, NumericVector comparison);
RcppExport SEXP _rankingQ_pairwise_indicator_cpp(SEXP targetSEXP, SEXP comparisonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type comparison(comparisonSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_indicator_cpp(target, comparison));
    return rcpp_result_gen;
END_RCPP
}
// topk_indicator_cpp
NumericVector topk_indicator_cpp(NumericVector ranks, int k);
RcppExport SEXP _rankingQ_topk_indicator_cpp(SEXP ranksSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(topk_indicator_cpp(ranks, k));
    return rcpp_result_gen;
END_RCPP
}
// marginal_indicator_cpp
NumericVector marginal_indicator_cpp(NumericVector ranks, int k);
RcppExport SEXP _rankingQ_marginal_indicator_cpp(SEXP ranksSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(marginal_indicator_cpp(ranks, k));
    return rcpp_result_gen;
END_RCPP
}
// bias_correct_cpp
double bias_correct_cpp(double estimate, double g_U, double p_non_random);
RcppExport SEXP _rankingQ_bias_correct_cpp(SEXP estimateSEXP, SEXP g_USEXP, SEXP p_non_randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type estimate(estimateSEXP);
    Rcpp::traits::input_parameter< double >::type g_U(g_USEXP);
    Rcpp::traits::input_parameter< double >::type p_non_random(p_non_randomSEXP);
    rcpp_result_gen = Rcpp::wrap(bias_correct_cpp(estimate, g_U, p_non_random));
    return rcpp_result_gen;
END_RCPP
}
// bias_correct_vec_cpp
NumericVector bias_correct_vec_cpp(NumericVector estimates, NumericVector g_U, double p_non_random);
RcppExport SEXP _rankingQ_bias_correct_vec_cpp(SEXP estimatesSEXP, SEXP g_USEXP, SEXP p_non_randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_U(g_USEXP);
    Rcpp::traits::input_parameter< double >::type p_non_random(p_non_randomSEXP);
    rcpp_result_gen = Rcpp::wrap(bias_correct_vec_cpp(estimates, g_U, p_non_random));
    return rcpp_result_gen;
END_RCPP
}
// prop_non_random_cpp
double prop_non_random_cpp(double prop_correct, int J);
RcppExport SEXP _rankingQ_prop_non_random_cpp(SEXP prop_correctSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prop_correct(prop_correctSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(prop_non_random_cpp(prop_correct, J));
    return rcpp_result_gen;
END_RCPP
}
// compute_qoi_stats_cpp
List compute_qoi_stats_cpp(NumericMatrix data, NumericVector weights, int J);
RcppExport SEXP _rankingQ_compute_qoi_stats_cpp(SEXP dataSEXP, SEXP weightsSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_qoi_stats_cpp(data, weights, J));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_qoi_cpp
List bootstrap_qoi_cpp(NumericMatrix data, NumericVector anc_correct, NumericVector weights, int J, int n_bootstrap, int seed);
RcppExport SEXP _rankingQ_bootstrap_qoi_cpp(SEXP dataSEXP, SEXP anc_correctSEXP, SEXP weightsSEXP, SEXP JSEXP, SEXP n_bootstrapSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anc_correct(anc_correctSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_qoi_cpp(data, anc_correct, weights, J, n_bootstrap, seed));
    return rcpp_result_gen;
END_RCPP
}
// weighted_table_cpp
NumericVector weighted_table_cpp(CharacterVector x, NumericVector weights);
RcppExport SEXP _rankingQ_weighted_table_cpp(SEXP xSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_table_cpp(x, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rankingQ_weighted_mean_cpp", (DL_FUNC) &_rankingQ_weighted_mean_cpp, 2},
    {"_rankingQ_weighted_var_cpp", (DL_FUNC) &_rankingQ_weighted_var_cpp, 2},
    {"_rankingQ_pairwise_indicator_cpp", (DL_FUNC) &_rankingQ_pairwise_indicator_cpp, 2},
    {"_rankingQ_topk_indicator_cpp", (DL_FUNC) &_rankingQ_topk_indicator_cpp, 2},
    {"_rankingQ_marginal_indicator_cpp", (DL_FUNC) &_rankingQ_marginal_indicator_cpp, 2},
    {"_rankingQ_bias_correct_cpp", (DL_FUNC) &_rankingQ_bias_correct_cpp, 3},
    {"_rankingQ_bias_correct_vec_cpp", (DL_FUNC) &_rankingQ_bias_correct_vec_cpp, 3},
    {"_rankingQ_prop_non_random_cpp", (DL_FUNC) &_rankingQ_prop_non_random_cpp, 2},
    {"_rankingQ_compute_qoi_stats_cpp", (DL_FUNC) &_rankingQ_compute_qoi_stats_cpp, 3},
    {"_rankingQ_bootstrap_qoi_cpp", (DL_FUNC) &_rankingQ_bootstrap_qoi_cpp, 6},
    {"_rankingQ_weighted_table_cpp", (DL_FUNC) &_rankingQ_weighted_table_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rankingQ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
