#' Compute the Average Rank of All Items
#'
#' This function calculates the average rank for the data frame that contains
#' ranking data. It can be used for both long- and wide-type data frames.
#'
#' @param x A data frame that contains rankings of items.
#' @param rankings The name of the column that contains the rankings.
#' Defaults to NULL, which means that the function will look for a data frame
#' with two columns, "item" and "rank".
#' @param items The name of the column that contains the items' names, or,
#' in case of a wide file, the item names in the reference choice set.
#' Defaults to NULL.
#' @param long The type of the data frame. Defaults to `FALSE`.
#' It `TRUE`, which means that the data frame is in
#' the long format, it is presumed to be generated by \code{rank_longer()}.
#' If the data frame is in the wide format, it should be set to `FALSE`.
#' This only accepts a data frame with a single ranking variable that
#' contains rankings, and the rankings should be in the form of a string
#' such as \code{"123"}.
#' @param raw If \code{TRUE}, the function will return the raw average rank.
#' If \code{FALSE}, the function will return the average rank after correcting
#' based on the IPW estimator. Defaults to \code{TRUE}.
#' @param weight The name of the column that contains the weights for the IPW
#' estimator. Defaults to \code{NULL}.
#' @param round The number of decimal places to round the output to.
#' Defaults to \code{NULL}.
#'
#' @returns A data frame with the average rank of each item in the
#' reference choice set.
#'
#' @importFrom dplyr group_by summarise across everything `%>%` mutate
#' select left_join rename
#' @importFrom tidyr pivot_longer separate_wider_position
#' @importFrom purrr imap
#' @importFrom rlang !! set_names
#' @importFrom tidyselect all_of
#' @importFrom stats sd
#' @importFrom estimatr lm_robust tidy
#'
#' @examples
#' x <- data.frame(
#'   id = c("Bernie", "Yuki", "Silvia"),
#'   rank = c("123", "321", "213")
#' )
#' avg_rank(x, "rank")
#' avg_rank(x, "rank", items = c("Money", "Power", "Respect"))
#'
#' y <- data.frame(rank = c("123", "321", "213"))
#' avg_rank(y, "rank")
#' z <- rank_longer(
#'   y,
#'   cols = "rank",
#'   reference = c("Money", "Power", "Respect")
#' )
#' avg_rank(z, "ranking", items = "item_name", long = TRUE)
#'
#' ## Example output from item_to_rank
#' x <- data.frame(
#'   item = c("a", "b", "c", "a", "b", "c", "a", "b", "c"),
#'   rank = c(3L, 1L, 2L, 1L, 2L, 3L, 3L, 2L, 1L)
#' )
#' avg_rank(x, long = TRUE)
#'
#' @export

avg_rank <- function(x,
                     rankings = NULL,
                     items = NULL,
                     long = FALSE,
                     raw = TRUE,
                     weight = NULL,
                     round = NULL) {
  ## Suppress "no visible binding for global variable" warnings
  . <- item <- item_name <- ranking <- lower <- upper <- se <- variable <-
    method <- std.error <- estimate <- conf.low <- conf.high <- outcome <-
    qoi <- NULL

  count_items <- function(items) {
    if (is.data.frame(items)) {
      return(nrow(items))
    }
    length(items)
  }
  select_named_columns <- function(data, cols) {
    keep_idx <- match(cols, names(data))
    out <- data[, unique(keep_idx), drop = FALSE]
    names(out) <- cols[!duplicated(keep_idx)]
    out
  }

  if (!is.logical(long) || length(long) != 1 || is.na(long)) {
    stop("The 'long' argument must be either TRUE or FALSE.")
  }
  if (!is.logical(raw) || length(raw) != 1 || is.na(raw)) {
    stop("The 'raw' argument must be either TRUE or FALSE.")
  }

  if (!raw && is.null(items)) {
    stop("If using the IPW estimator, the items variable must be specified.")
  }
  if (!raw && is.null(weight)) {
    stop("If using the IPW estimator, the weight variable must be specified.")
  }
  if (!raw && long) {
    stop("If using the IPW estimator, the data frame must be in wide format.")
  }
  if (raw && !is.null(weight)) {
    stop("If not using the IPW estimator, the weight variable must be NULL.")
  }
  if (!is.null(weight)) {
    if (!(weight %in% names(x))) {
      stop("The weight variable is not contained in the given data frame.")
    }
  }

  ## Use the output from `item_to_rank` without having to specify input.
  if (
    is.null(rankings) && is.null(items) &&
      ncol(x) == 2 && ("rank" %in% names(x)) && ("item" %in% names(x))
  ) {
    rankings <- "rank"
    items <- "item"
  }

  if (is.null(rankings) && !long && ("rank" %in% names(x))) {
    rankings <- "rank"
  }

  if (is.null(rankings) && !("rank" %in% names(x)) && raw) {
    stop("The rankings variable must be specified.")
  }

  ## Class sanity checks
  if (!("data.frame" %in% class(x))) {
    stop("x must be a data frame.")
  }
  if (!is.null(rankings)) {
    if (!("character" %in% class(rankings))) {
      stop("The rankings variable must be a character.")
    }
    if (!(rankings %in% colnames(x))) {
      stop("The rankings variable is not contained in the given data frame.")
    }
  }

  ## What is the J?
  if (long) {
    if (is.null(items)) {
      stop("If long data frame, the items variable must be specified.")
    }
    if (!(items %in% colnames(x))) {
      stop("The items variable is not contained in the given data frame.")
    }
    J <- length(unique(x[[items]]))
  } else if (!is.null(rankings)) {
    J <- .infer_ranking_size(x[[rankings]])
  } else if (!is.null(items)) {
    J <- count_items(items)
  } else {
    stop(
      "There is no information about the number of items in the data frame."
    )
  }

  ## Sanity checks for "rankings" and "items" arguments.
  if (!is.null(items)) {
    if (!long) {
      if (J != count_items(items)) {
        stop(
          paste0(
            "The number of reference choice set's elements in the items ",
            "variable does not match the number of items ranked."
          )
        )
      }
    } else {
      if (!(items %in% colnames(x))) {
        stop("The items variable is not contained in the given data frame.")
      }
    }
  } else {
      if (long) {
      stop("If long data frame, the items variable must be specified.")
    }
  }

  ## Depending on whether it's a long- or wide-type data frame,
  ## treat differently
  if (raw) {
    if (long) {
      out <- select_named_columns(x, c(items, rankings)) %>%
        group_by(!!as.name(items))
    } else {
      if (is.data.frame(items)) {
        stop(
          paste(
            "For raw wide data, items must be either NULL or a character",
            "vector of item labels."
          )
        )
      }

      reference_items <- if (is.null(items)) ordinal_seq(J) else items
      out <- suppressMessages(
        rank_longer(
          select_named_columns(x, rankings),
          cols = rankings,
          reference = reference_items
        )
      ) %>%
        rename(
          item = item_name,
          rankings = ranking
        ) %>%
        mutate(item = factor(item, levels = reference_items))
      rankings <- "rankings"
      out <- out %>%
        group_by(item) %>%
        select(item, !!as.name(rankings))
    }

    ## Compute the average rank and the 95% CI
    out <- out %>%
      summarise(
        qoi = "Average Rank",
        mean = mean(!!as.name(rankings), na.rm = TRUE),
        se = {
          n_obs <- sum(!is.na(!!as.name(rankings)))
          if (n_obs > 1) {
            sd(!!as.name(rankings), na.rm = TRUE) / sqrt(n_obs)
          } else {
            NA_real_
          }
        },
        lower = mean - 1.96 * se,
        upper = mean + 1.96 * se,
        method = "Raw Data"
      )
    if (is.null(items)) {
      out$item <- as.character(out$item)
    }
  } else {
    vars <- items
    if (is.data.frame(items)) {
      if (all(sort(colnames(items)) == c("item", "variable"))) {
        vars <- items$variable
      } else {
        stop(
          paste0(
            paste(
              "If items argument is a data frame, make sure that the",
              "columns are"
            ),
            " named 'item' and 'variable'."
          )
        )
      }
    }

    out <- vars %>%
      set_names(., .) %>%
      imap(
        ~ lm_robust(
          !!as.name(.x) ~ 1,
          weights = !!as.name(weight),
          data = select_named_columns(x, c(.x, weight))
        ) %>%
          tidy() %>%
          mutate(outcome = .y)
      ) %>%
      Reduce(rbind, .) %>%
      mutate(
        mean = estimate,
        se = std.error,
        lower = conf.low,
        upper = conf.high,
        item = outcome,
        qoi = "Average Rank"
      ) %>%
      mutate(method = "IPW")

    if (is.data.frame(items)) {
      out <- out %>%
        rename(variable = item) %>%
        left_join(items, by = "variable") %>%
        select(-variable)
      items <- items$item
    }

    out <- out %>%
      mutate(item = factor(item, levels = items))
  }

  if (!is.null(items) && !long) {
    ## Must align the summary output by the item order given;
    ## otherwise, the summary tibble appears in alphabetical order
    out$item <- factor(out$item, levels = items)
    out <- out[order(out$item), ]
  }

  ## When printing, round if specified
  if (!is.null(round)) {
    out <- out %>%
      mutate(across(c(mean, lower, upper), ~ round(., digits = round)))
  }

  if (long) {
    return(
      as.data.frame(out) %>%
        select(!!items, qoi, mean, se, lower, upper, method)
    )
  } else {
    return(
      as.data.frame(out) %>% select(item, qoi, mean, se, lower, upper, method)
    )
  }
}
