#' Compute the Average Rank of All Items
#'
#' This function calculates the average rank for the data frame that contains
#' ranking data. It can be used for both long- and wide-type data frames.
#'
#' @param x A data frame that contains rankings of items.
#' @param rankings The name of the column that contains the rankings.
#' Defaults to NULL, which means that the function will look for a data frame
#' with two columns, "item" and "rank". For wide data, this can also be a
#' character vector of separate ranking columns such as
#' \code{c("apple", "orange", "banana")}.
#' @param items The name of the column that contains the items' names, or,
#' in case of a wide file, the item names in the reference choice set.
#' Defaults to NULL.
#' @param long The type of the data frame. Defaults to `FALSE`.
#' It `TRUE`, which means that the data frame is in
#' the long format, it is presumed to be generated by \code{rank_longer()}.
#' If the data frame is in the wide format, it should be set to `FALSE`.
#' For wide data, rankings can be supplied either as a single encoded
#' ranking string such as \code{"123"} or as separate ranking columns.
#' @param raw If \code{TRUE}, the function will return the raw average rank.
#' If \code{FALSE}, the function will return the average rank after correcting
#' based on the IPW estimator. Defaults to \code{TRUE}.
#' @param weight Optional weight specification. This can be the name of a
#' weight column in \code{x} or a numeric vector with one weight per row.
#' Defaults to \code{NULL}.
#' @param round The number of decimal places to round the output to.
#' Defaults to \code{NULL}.
#'
#' @returns A data frame with the average rank of each item in the
#' reference choice set.
#'
#' @importFrom dplyr group_by summarise across everything `%>%` mutate
#' select left_join rename
#' @importFrom tidyr pivot_longer separate_wider_position
#' @importFrom purrr imap
#' @importFrom rlang !! set_names
#' @importFrom tidyselect all_of
#' @importFrom stats sd
#' @importFrom estimatr lm_robust
#' @importFrom generics tidy
#'
#' @examples
#' x <- data.frame(
#'   id = c("Bernie", "Yuki", "Silvia"),
#'   rank = c("123", "321", "213")
#' )
#' avg_rank(x, "rank")
#' avg_rank(x, "rank", items = c("Money", "Power", "Respect"))
#'
#' y <- data.frame(rank = c("123", "321", "213"))
#' avg_rank(y, "rank")
#'
#' x_sep <- data.frame(
#'   apple = c(2, 1, 3),
#'   orange = c(1, 3, 2),
#'   banana = c(3, 2, 1)
#' )
#' avg_rank(x_sep, rankings = c("apple", "orange", "banana"))
#'
#' x_weighted <- data.frame(
#'   rank = c("12", "21"),
#'   survey_weight = c(1, 3)
#' )
#' avg_rank(x_weighted, "rank", weight = "survey_weight")
#' z <- rank_longer(
#'   y,
#'   cols = "rank",
#'   reference = c("Money", "Power", "Respect")
#' )
#' avg_rank(z, "ranking", items = "item_name", long = TRUE)
#'
#' ## Example output from item_to_rank
#' x <- data.frame(
#'   item = c("a", "b", "c", "a", "b", "c", "a", "b", "c"),
#'   rank = c(3L, 1L, 2L, 1L, 2L, 3L, 3L, 2L, 1L)
#' )
#' avg_rank(x, long = TRUE)
#'
#' @export

avg_rank <- function(x,
                     rankings = NULL,
                     items = NULL,
                     long = FALSE,
                     raw = TRUE,
                     weight = NULL,
                     round = NULL) {
  ## Suppress "no visible binding for global variable" warnings
  . <- item <- item_name <- ranking <- lower <- upper <- se <- variable <-
    method <- std.error <- estimate <- conf.low <- conf.high <- outcome <-
    qoi <- NULL
  items_input <- items
  item_levels_out <- NULL

  count_items <- function(items) {
    if (is.data.frame(items)) {
      return(nrow(items))
    }
    length(items)
  }
  summarize_avg_rank <- function(data, group_var, ranking_var, weight_var = NULL) {
    if (is.null(weight_var)) {
      return(
        data %>%
          group_by(!!as.name(group_var)) %>%
          summarise(
            qoi = "Average Rank",
            mean = mean(!!as.name(ranking_var), na.rm = TRUE),
            se = {
              n_obs <- sum(!is.na(!!as.name(ranking_var)))
              if (n_obs > 1) {
                sd(!!as.name(ranking_var), na.rm = TRUE) / sqrt(n_obs)
              } else {
                NA_real_
              }
            },
            lower = mean - 1.96 * se,
            upper = mean + 1.96 * se,
            method = "Raw Data"
          )
      )
    }

    split(data, data[[group_var]]) %>%
      imap(
        ~ {
          fit_data <- data.frame(
            y = .x[[ranking_var]],
            w = .x[[weight_var]]
          )
          fit_data <- fit_data[complete.cases(fit_data), , drop = FALSE]

          if (nrow(fit_data) == 0) {
            return(
              data.frame(
                outcome = .y,
                estimate = NA_real_,
                std.error = NA_real_,
                conf.low = NA_real_,
                conf.high = NA_real_
              )
            )
          }

          lm_robust(y ~ 1, data = fit_data, weights = w) %>%
            tidy() %>%
            mutate(outcome = .y)
        }
      ) %>%
      Reduce(rbind, .) %>%
      mutate(
        mean = estimate,
        se = std.error,
        lower = conf.low,
        upper = conf.high,
        qoi = "Average Rank",
        method = "Raw Data"
      ) -> out

    names(out)[names(out) == "outcome"] <- group_var
    out %>%
      select(
        !!as.name(group_var),
        qoi,
        mean,
        se,
        lower,
        upper,
        method
      )
  }
  select_named_columns <- function(data, cols) {
    keep_idx <- match(cols, names(data))
    out <- data[, unique(keep_idx), drop = FALSE]
    names(out) <- cols[!duplicated(keep_idx)]
    out
  }

  if (!is.logical(long) || length(long) != 1 || is.na(long)) {
    stop("The 'long' argument must be either TRUE or FALSE.")
  }
  if (!is.logical(raw) || length(raw) != 1 || is.na(raw)) {
    stop("The 'raw' argument must be either TRUE or FALSE.")
  }

  if (!raw && is.null(items)) {
    stop("If using the IPW estimator, the items variable must be specified.")
  }
  if (!raw && is.null(weight)) {
    stop("If using the IPW estimator, the weight variable must be specified.")
  }
  if (!raw && long) {
    stop("If using the IPW estimator, the data frame must be in wide format.")
  }

  ## Use the output from `item_to_rank` without having to specify input.
  if (
    is.null(rankings) && is.null(items) &&
      ncol(x) == 2 && ("rank" %in% names(x)) && ("item" %in% names(x))
  ) {
    rankings <- "rank"
    items <- "item"
  }

  if (is.null(rankings) && !long && ("rank" %in% names(x))) {
    rankings <- "rank"
  }

  if (is.null(rankings) && !("rank" %in% names(x)) && raw) {
    stop("The rankings variable must be specified.")
  }

  ## Class sanity checks
  if (!("data.frame" %in% class(x))) {
    stop("x must be a data frame.")
  }
  if (!is.null(weight)) {
    weight <- .resolve_weight_vector(x, weight, nrow(x))
    x[[".tmp_weight"]] <- weight
    weight <- ".tmp_weight"
  }
  if (!is.null(rankings)) {
    if (!("character" %in% class(rankings)) ||
        length(rankings) < 1 ||
        anyNA(rankings)) {
      stop("The rankings variable must be a character.")
    }
    if (!all(rankings %in% colnames(x))) {
      stop("The rankings variable is not contained in the given data frame.")
    }
    if (long && length(rankings) != 1) {
      stop("If long data frame, the rankings variable must be a single column name.")
    }
  }

  ## What is the J?
  if (long) {
    if (is.null(items)) {
      stop("If long data frame, the items variable must be specified.")
    }
    if (!(items %in% colnames(x))) {
      stop("The items variable is not contained in the given data frame.")
    }
    J <- length(unique(x[[items]]))
  } else if (!is.null(rankings)) {
    if (length(rankings) == 1) {
      J <- .infer_ranking_size(x[[rankings]])
    } else {
      J <- length(rankings)
    }
  } else if (!is.null(items)) {
    J <- count_items(items)
  } else {
    stop(
      "There is no information about the number of items in the data frame."
    )
  }

  ## Sanity checks for "rankings" and "items" arguments.
  if (!is.null(items)) {
    if (!long) {
      if (J != count_items(items)) {
        stop(
          paste0(
            "The number of reference choice set's elements in the items ",
            "variable does not match the number of items ranked."
          )
        )
      }
    } else {
      if (!(items %in% colnames(x))) {
        stop("The items variable is not contained in the given data frame.")
      }
    }
  } else {
      if (long) {
      stop("If long data frame, the items variable must be specified.")
    }
  }

  ## Depending on whether it's a long- or wide-type data frame,
  ## treat differently
  if (raw) {
    if (long) {
      out <- select_named_columns(
        x,
        c(items, rankings, if (!is.null(weight)) weight)
      )
      out[[items]] <- factor(out[[items]], levels = unique(out[[items]]))
      group_var <- items
    } else {
      if (is.data.frame(items)) {
        stop(
          paste(
            "For raw wide data, items must be either NULL or a character",
            "vector of item labels."
          )
        )
      }

      if (length(rankings) == 1) {
        reference_items <- if (is.null(items)) ordinal_seq(J) else items
        parsed_rankings <- .parse_ranking_vector(x[[rankings]], J = J)
        rank_df <- as.data.frame(parsed_rankings$values, stringsAsFactors = FALSE)
        names(rank_df) <- reference_items
      } else {
        reference_items <- if (is.null(items)) rankings else items
        rank_df <- select_named_columns(x, rankings)
        names(rank_df) <- reference_items
      }

      out <- data.frame(rank_df, check.names = FALSE)
      if (!is.null(weight)) {
        out[[weight]] <- x[[weight]]
      }
      out <- out %>%
        pivot_longer(
          cols = all_of(reference_items),
          names_to = "item",
          values_to = "rankings"
        ) %>%
        mutate(item = factor(item, levels = reference_items))
      rankings <- "rankings"
      group_var <- "item"
      item_levels_out <- reference_items
    }

    out <- summarize_avg_rank(out, group_var, rankings, weight)
  } else {
    vars <- items
    if (is.data.frame(items)) {
      if (all(sort(colnames(items)) == c("item", "variable"))) {
        vars <- items$variable
      } else {
        stop(
          paste0(
            paste(
              "If items argument is a data frame, make sure that the",
              "columns are"
            ),
            " named 'item' and 'variable'."
          )
        )
      }
    }

    out <- vars %>%
      set_names(., .) %>%
      imap(
        ~ lm_robust(
          !!as.name(.x) ~ 1,
          weights = !!as.name(weight),
          data = select_named_columns(x, c(.x, weight))
        ) %>%
          tidy() %>%
          mutate(outcome = .y)
      ) %>%
      Reduce(rbind, .) %>%
      mutate(
        mean = estimate,
        se = std.error,
        lower = conf.low,
        upper = conf.high,
        item = outcome,
        qoi = "Average Rank"
      ) %>%
      mutate(method = "IPW")

    if (is.data.frame(items)) {
      out <- out %>%
        rename(variable = item) %>%
        left_join(items, by = "variable") %>%
        select(-variable)
      items <- items$item
    }

    item_levels_out <- items
    out <- out %>%
      mutate(item = factor(item, levels = items))
  }

  if (!long && !is.null(item_levels_out)) {
    ## Must align the summary output by the item order given;
    ## otherwise, the summary tibble appears in alphabetical order
    out$item <- factor(out$item, levels = item_levels_out)
    out <- out[order(out$item), ]
  }
  if (!long && is.null(items_input)) {
    out$item <- as.character(out$item)
  }

  ## When printing, round if specified
  if (!is.null(round)) {
    out <- out %>%
      mutate(across(c(mean, lower, upper), ~ round(., digits = round)))
  }

  if (long) {
    out[[items]] <- as.character(out[[items]])
    return(
      as.data.frame(out) %>%
        select(!!items, qoi, mean, se, lower, upper, method)
    )
  } else {
    return(
      as.data.frame(out) %>% select(item, qoi, mean, se, lower, upper, method)
    )
  }
}
