# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_mean_cpp <- function(x, weights) {
    .Call(`_rankingQ_weighted_mean_cpp`, x, weights)
}

weighted_var_cpp <- function(x, weights) {
    .Call(`_rankingQ_weighted_var_cpp`, x, weights)
}

pairwise_indicator_cpp <- function(target, comparison) {
    .Call(`_rankingQ_pairwise_indicator_cpp`, target, comparison)
}

topk_indicator_cpp <- function(ranks, k) {
    .Call(`_rankingQ_topk_indicator_cpp`, ranks, k)
}

marginal_indicator_cpp <- function(ranks, k) {
    .Call(`_rankingQ_marginal_indicator_cpp`, ranks, k)
}

bias_correct_cpp <- function(estimate, g_U, p_non_random) {
    .Call(`_rankingQ_bias_correct_cpp`, estimate, g_U, p_non_random)
}

bias_correct_vec_cpp <- function(estimates, g_U, p_non_random) {
    .Call(`_rankingQ_bias_correct_vec_cpp`, estimates, g_U, p_non_random)
}

prop_non_random_cpp <- function(prop_correct, J) {
    .Call(`_rankingQ_prop_non_random_cpp`, prop_correct, J)
}

compute_qoi_stats_cpp <- function(data, weights, J) {
    .Call(`_rankingQ_compute_qoi_stats_cpp`, data, weights, J)
}

bootstrap_qoi_cpp <- function(data, anc_correct, weights, J, n_bootstrap, seed) {
    .Call(`_rankingQ_bootstrap_qoi_cpp`, data, anc_correct, weights, J, n_bootstrap, seed)
}

weighted_table_cpp <- function(x, weights) {
    .Call(`_rankingQ_weighted_table_cpp`, x, weights)
}

